language: csharp
mono: none
dotnet: 2.1
dist: trusty

solution: KenticoCloudDocsGithubService.sln

cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
    - '$HOME/.sonar/cache'

jobs:
  include:
    - stage: "Tests"
      install:
        - dotnet tool install --global dotnet-sonarscanner
        - dotnet restore
      before_script:
        - export PATH="$PATH:$HOME/.dotnet/tools"
      script:
        - dotnet sonarscanner begin /k:"kentico-cloud-docs-github-sync" /n:"GitHub Sync" /v:"1.0.0" /o:"kentico-cloud-docs" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.language="cs" /d:sonar.branch.name="$TRAVIS_BRANCH" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml" || true
        - dotnet build
        - dotnet test GithubService.Services.Tests/GithubService.Services.Tests.csproj "--logger:trx;LogFileName=results.trx"
        - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" || true
    - stage: "Deployment"
      if: type != pull_request AND (branch = master OR branch = develop)
      before_install: chmod +rx .travis/deploy.sh
      script: .travis/deploy.sh
