language: csharp
mono: none
dotnet: 2.1
dist: trusty

solution: KenticoCloudDocsGithubService.sln

git:
  depth: false

env:  
  global:
    - SONAR_CONFIG_PATH="$TRAVIS_BUILD_DIR/sonar-cloud.xml"

jobs:
  include:
    - stage: "Build and Tests"

      before_install:
        - chmod +rx .travis/sonar-configurator.sh

      install:
        - .travis/sonar-configurator.sh "$SONAR_CONFIG_PATH"
        - dotnet tool install --global dotnet-sonarscanner
        - export PATH="$PATH:$HOME/.dotnet/tools"
        - dotnet restore
      
      script:
        - dotnet sonarscanner begin /k:"Kentico_kentico-cloud-docs-github-sync" /d:sonar.login="$SONAR_TOKEN" /s:"$SONAR_CONFIG_PATH"
        - dotnet build
        - dotnet test GithubService.Services.Tests/GithubService.Services.Tests.csproj "--logger:trx;LogFileName=results.trx"
        - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
    
    - stage: "Deployment"
      if: type != pull_request AND (branch = master OR branch = develop)

      before_script: 
        - chmod +rx .travis/deploy.sh

      script: 
        - .travis/deploy.sh

cache:
  directories:
    - "$HOME/.nuget/packages"
    - "$HOME/.local/share/NuGet/Cache"
    - "$HOME/.sonar/cache"
