language: csharp
mono: none
dotnet: 2.2
dist: xenial

solution: KenticoCloudDocsGithubService.sln

git:
  depth: false

env:  
  global:
    - SONAR_CONFIG_PATH="$TRAVIS_BUILD_DIR/sonar-cloud.xml"

jobs:
  include:
    - stage: "Build and Tests"

      before_install:
        - export PATH="$PATH:$HOME/.dotnet/tools"
        - chmod +rx .travis/sonar-configurator.sh

      install:
        - .travis/sonar-configurator.sh "$SONAR_CONFIG_PATH"
        - dotnet tool install --global dotnet-sonarscanner
        - dotnet restore

      script:
        - dotnet sonarscanner begin /k:"KenticoDocs_kontent-docs-github-reader" /o:"kenticodocs" /d:sonar.login="$SONAR_TOKEN" /s:"$SONAR_CONFIG_PATH"
        - dotnet build
        - >
            dotnet test
            --no-build
            --logger:"trx;LogFileName=$TRAVIS_BUILD_DIR/tests_results.trx"
            /p:CollectCoverage=true
            /p:CoverletOutputFormat='json%2copencover'
            /p:CoverletOutput="$TRAVIS_BUILD_DIR/coverage_results"
            /p:MergeWith="$TRAVIS_BUILD_DIR/coverage_results.json"
        - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

    - stage: "Deployment"
      if: type != pull_request AND (branch = master OR branch = develop)

      before_script: 
        - chmod +rx .travis/deploy.sh

      script: 
        - .travis/deploy.sh

cache:
  directories:
    - "$HOME/.nuget/packages"
    - "$HOME/.local/share/NuGet/Cache"
    - "$HOME/.sonar/cache"
